### ISSUE TITLE
Static resources are not loading sometimes

### ISSUE THREAD

**Issue by oxalorg** [lambdaisland/gaiwan_co#30]
Sometimes I get this error:

```
2022-06-09 12:49:17.766 WARN  org.eclipse.jetty.server.HttpChannel - /favicon-16x16.png
java.lang.IllegalStateException: Multi threaded access requested by thread Thread[qtp175317715-72,5,main] but is not allowed for language(s) js.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:940)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:799)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:629)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:1885)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:112)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callProfiled(DefaultRuntimeAccessor.java:147)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.execute(PolyglotValueDispatch.java:2369)
	at org.graalvm.polyglot.Value.execute(Value.java:841)
	at nextjournal.markdown$make_js_fn$fn__14492.doInvoke(markdown.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at nextjournal.markdown$tokenize.invokeStatic(markdown.clj:48)
	at nextjournal.markdown$tokenize.invoke(markdown.clj:47)
	at nextjournal.markdown$parse.invokeStatic(markdown.clj:53)
	at nextjournal.markdown$parse.invoke(markdown.clj:51)
	at nextjournal.markdown$__GT_hiccup.invokeStatic(markdown.clj:58)
	at nextjournal.markdown$__GT_hiccup.invoke(markdown.clj:55)
	at co.gaiwan.site.md_files$read_md_PLUS_meta.invokeStatic(NO_SOURCE_FILE:28)
	at co.gaiwan.site.md_files$read_md_PLUS_meta.invoke(NO_SOURCE_FILE:22)
	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$transduce.invokeStatic(core.clj:6947)
	at clojure.core$into.invokeStatic(core.clj:6962)
	at clojure.core$into.invoke(core.clj:6950)
	at co.gaiwan.site.md_files$slurp_files.invokeStatic(NO_SOURCE_FILE:40)
	at co.gaiwan.site.md_files$slurp_files.invoke(NO_SOURCE_FILE:37)
	at co.gaiwan.site.md_files$slurp_dir.invokeStatic(md_files.clj:49)
	at co.gaiwan.site.md_files$slurp_dir.invoke(md_files.clj:46)
	at co.gaiwan.site.pages$routes.invokeStatic(pages.clj:26)
	at co.gaiwan.site.pages$routes.invoke(pages.clj:25)
	at co.gaiwan.site.routes$routes.invokeStatic(routes.clj:60)
	at co.gaiwan.site.routes$routes.invoke(routes.clj:38)
	at co.gaiwan.site.http$build_handler.invokeStatic(http.clj:30)
	at co.gaiwan.site.http$build_handler.invoke(http.clj:29)
	at clojure.lang.Var.invoke(Var.java:380)
	at clojure.core$comp$fn__5876.invoke(core.clj:2585)
	at lambdaisland.webstuff.http$start_jetty_BANG_$fn__25355.invoke(http.clj:268)
	at ring.adapter.jetty$proxy_handler$fn__25252.invoke(jetty.clj:27)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace: null
```

All static requests are failing:

![image](https://user-images.githubusercontent.com/4194289/172788901-97bc5683-6bc9-41e1-8444-504f265b7510.png)

The culprit is specifically the nextjournal markdown renderer which uses graaljs?

**Comment by oxalorg** [comment]
Okay looks like nextjournal/markdown has moved here: https://github.com/nextjournal/markdown 

Updated to latest version, and changed some api calls, getting another error now. Figuring it out

**Comment by oxalorg** [comment]
https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b

Turns out this was happening because in dev mode we rebuild the http-handler for every request, which recomputes the `routes`, which in turn triggers markdown rendering again for all static resources being requested (all at the same time) which leads to some sort of Thread sharing of context

I tried caching and it worked but that wasn't the best solution because then we lose REPLability.

I think I resolved it with a lock for rendering markdown. I don't think this should have any consequences on build time (since we won't be rebuilding routes like we do in dev, and neither do we build with multiple threads yet)
